name:                hrf
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hrf#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
  - README.md

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - TemplateHaskell
  - TypeFamilies
  - FlexibleContexts
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - GADTs
  - EmptyDataDecls
  - QuasiQuotes

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - monad-logger
  - warp
  - wai
  - persistent
  - persistent-template
  - persistent-sqlite
  - persistent-postgresql
  - containers
  - resource-pool
  - esqueleto
  - swagger2
  - servant
  - servant-swagger
  - servant-swagger-ui
  - servant-server

library:
  source-dirs:
    - src


executables:
  hrf:
    source-dirs:      exe
    main:             Main.hs
    dependencies:
      - hrf


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - hspec
      - hrf
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
